/**
 * GoalSwap Arena — Country Flag Lookup
 *
 * Maps country names → ISO 3166-1 alpha-2 codes (lowercase) for flag SVGs.
 * Also maps common league names to their country codes.
 */

// ── Country Name → ISO Code ─────────────────────────────────────────
// Covers all FIFA member nations plus common variants
const COUNTRY_MAP: Record<string, string> = {
  // A
  afghanistan: "af",
  albania: "al",
  algeria: "dz",
  "american samoa": "as",
  andorra: "ad",
  angola: "ao",
  "antigua and barbuda": "ag",
  argentina: "ar",
  armenia: "am",
  aruba: "aw",
  australia: "au",
  austria: "at",
  azerbaijan: "az",
  // B
  bahamas: "bs",
  bahrain: "bh",
  bangladesh: "bd",
  barbados: "bb",
  belarus: "by",
  belgium: "be",
  belize: "bz",
  benin: "bj",
  bermuda: "bm",
  bhutan: "bt",
  bolivia: "bo",
  "bosnia and herzegovina": "ba",
  botswana: "bw",
  brazil: "br",
  "british virgin islands": "vg",
  brunei: "bn",
  bulgaria: "bg",
  "burkina faso": "bf",
  burundi: "bi",
  // C
  "cabo verde": "cv",
  cambodia: "kh",
  cameroon: "cm",
  canada: "ca",
  "cayman islands": "ky",
  "central african republic": "cf",
  chad: "td",
  chile: "cl",
  china: "cn",
  "chinese taipei": "tw",
  colombia: "co",
  comoros: "km",
  "congo": "cg",
  "congo dr": "cd",
  "costa rica": "cr",
  "côte d'ivoire": "ci",
  "ivory coast": "ci",
  croatia: "hr",
  cuba: "cu",
  cyprus: "cy",
  "czech republic": "cz",
  czechia: "cz",
  // D
  denmark: "dk",
  djibouti: "dj",
  dominica: "dm",
  "dominican republic": "do",
  // E
  ecuador: "ec",
  egypt: "eg",
  "el salvador": "sv",
  "equatorial guinea": "gq",
  eritrea: "er",
  estonia: "ee",
  eswatini: "sz",
  ethiopia: "et",
  // F
  "falkland islands": "fk",
  "faroe islands": "fo",
  fiji: "fj",
  finland: "fi",
  france: "fr",
  "french guiana": "gf",
  "french polynesia": "pf",
  // G
  gabon: "ga",
  gambia: "gm",
  georgia: "ge",
  germany: "de",
  ghana: "gh",
  gibraltar: "gi",
  greece: "gr",
  greenland: "gl",
  grenada: "gd",
  guadeloupe: "gp",
  guam: "gu",
  guatemala: "gt",
  guinea: "gn",
  "guinea-bissau": "gw",
  guyana: "gy",
  // H
  haiti: "ht",
  honduras: "hn",
  "hong kong": "hk",
  hungary: "hu",
  // I
  iceland: "is",
  india: "in",
  indonesia: "id",
  iran: "ir",
  iraq: "iq",
  ireland: "ie",
  israel: "il",
  italy: "it",
  // J
  jamaica: "jm",
  japan: "jp",
  jordan: "jo",
  // K
  kazakhstan: "kz",
  kenya: "ke",
  kosovo: "xk",
  kuwait: "kw",
  kyrgyzstan: "kg",
  // L
  laos: "la",
  latvia: "lv",
  lebanon: "lb",
  lesotho: "ls",
  liberia: "lr",
  libya: "ly",
  liechtenstein: "li",
  lithuania: "lt",
  luxembourg: "lu",
  // M
  macau: "mo",
  madagascar: "mg",
  malawi: "mw",
  malaysia: "my",
  maldives: "mv",
  mali: "ml",
  malta: "mt",
  "martinique": "mq",
  mauritania: "mr",
  mauritius: "mu",
  mayotte: "yt",
  mexico: "mx",
  moldova: "md",
  monaco: "mc",
  mongolia: "mn",
  montenegro: "me",
  montserrat: "ms",
  morocco: "ma",
  mozambique: "mz",
  myanmar: "mm",
  // N
  namibia: "na",
  nepal: "np",
  netherlands: "nl",
  "new caledonia": "nc",
  "new zealand": "nz",
  nicaragua: "ni",
  niger: "ne",
  nigeria: "ng",
  "north korea": "kp",
  "north macedonia": "mk",
  "northern ireland": "gb-nir",
  norway: "no",
  // O
  oman: "om",
  // P
  pakistan: "pk",
  palestine: "ps",
  panama: "pa",
  "papua new guinea": "pg",
  paraguay: "py",
  peru: "pe",
  philippines: "ph",
  poland: "pl",
  portugal: "pt",
  "puerto rico": "pr",
  // Q
  qatar: "qa",
  // R
  romania: "ro",
  russia: "ru",
  rwanda: "rw",
  réunion: "re",
  // S
  "saudi arabia": "sa",
  scotland: "gb-sct",
  senegal: "sn",
  serbia: "rs",
  seychelles: "sc",
  "sierra leone": "sl",
  singapore: "sg",
  slovakia: "sk",
  slovenia: "si",
  "solomon islands": "sb",
  somalia: "so",
  "south africa": "za",
  "south korea": "kr",
  "south sudan": "ss",
  spain: "es",
  "sri lanka": "lk",
  "st. lucia": "lc",
  sudan: "sd",
  suriname: "sr",
  sweden: "se",
  switzerland: "ch",
  syria: "sy",
  // T
  "taiwan": "tw",
  tajikistan: "tj",
  tanzania: "tz",
  thailand: "th",
  "timor-leste": "tl",
  togo: "tg",
  tonga: "to",
  "trinidad and tobago": "tt",
  tunisia: "tn",
  turkey: "tr",
  turkmenistan: "tm",
  "turks and caicos islands": "tc",
  // U
  uganda: "ug",
  ukraine: "ua",
  "united arab emirates": "ae",
  "united kingdom": "gb",
  england: "gb-eng",
  "united states": "us",
  "usa": "us",
  uruguay: "uy",
  uzbekistan: "uz",
  // V
  vanuatu: "vu",
  "vatican city": "va",
  venezuela: "ve",
  vietnam: "vn",
  "virgin islands": "vi",
  // W
  wales: "gb-wls",
  // Y
  yemen: "ye",
  // Z
  zambia: "zm",
  zimbabwe: "zw",
  // European Union (not a country, but common)
  "european union": "eu",
};

// ── Team Name → Country Code ────────────────────────────────────────
// Maps popular football club names to their country so country flags
// show for club teams, not just national sides.
const TEAM_COUNTRY_MAP: Record<string, string> = {
  // Spain
  "real madrid": "es",
  "real madrid cf": "es",
  barcelona: "es",
  "fc barcelona": "es",
  "barcelona fc": "es",
  "atletico madrid": "es",
  "club atlético de madrid": "es",
  sevilla: "es",
  "sevilla fc": "es",
  valencia: "es",
  "valencia cf": "es",
  "athletic bilbao": "es",
  villarreal: "es",
  "villarreal cf": "es",
  "real sociedad": "es",
  "real betis": "es",
  "real betis balompié": "es",
  "celta vigo": "es",
  "levante ud": "es",
  "rayo vallecano": "es",
  osasuna: "es",
  espanyol: "es",
  "rcd espanyol": "es",
  granada: "es",
  mallorca: "es",
  alaves: "es",
  getafe: "es",
  "cadiz cf": "es",
  "elche cf": "es",
  // England
  "manchester united": "gb-eng",
  "manchester united fc": "gb-eng",
  "manchester city": "gb-eng",
  "manchester city fc": "gb-eng",
  liverpool: "gb-eng",
  "liverpool fc": "gb-eng",
  arsenal: "gb-eng",
  "arsenal fc": "gb-eng",
  chelsea: "gb-eng",
  "chelsea fc": "gb-eng",
  tottenham: "gb-eng",
  "tottenham hotspur": "gb-eng",
  "tottenham hotspur fc": "gb-eng",
  "newcastle united": "gb-eng",
  "newcastle united fc": "gb-eng",
  "aston villa": "gb-eng",
  "aston villa fc": "gb-eng",
  everton: "gb-eng",
  "everton fc": "gb-eng",
  "west ham united": "gb-eng",
  "west ham": "gb-eng",
  leicester: "gb-eng",
  "leicester city": "gb-eng",
  "leicester city fc": "gb-eng",
  wolverhampton: "gb-eng",
  "wolverhampton wanderers": "gb-eng",
  wolves: "gb-eng",
  brighton: "gb-eng",
  "brighton & hove albion": "gb-eng",
  "crystal palace": "gb-eng",
  fulham: "gb-eng",
  "fulham fc": "gb-eng",
  southampton: "gb-eng",
  "southampton fc": "gb-eng",
  "nottingham forest": "gb-eng",
  brentford: "gb-eng",
  "afc bournemouth": "gb-eng",
  bournemouth: "gb-eng",
  norwich: "gb-eng",
  "norwich city": "gb-eng",
  "leeds united": "gb-eng",
  derby: "gb-eng",
  "derby county": "gb-eng",
  "stoke city": "gb-eng",
  "west bromwich albion": "gb-eng",
  // Italy
  juventus: "it",
  "juventus fc": "it",
  "ac milan": "it",
  "milan ac": "it",
  "inter milan": "it",
  "fc internaazionale milano": "it",
  "inter": "it",
  "as roma": "it",
  roma: "it",
  lazio: "it",
  "ss lazio": "it",
  napoli: "it",
  "ssc napoli": "it",
  atalanta: "it",
  "atalanta bc": "it",
  fiorentina: "it",
  "acf fiorentina": "it",
  torino: "it",
  "torino fc": "it",
  bologna: "it",
  udinese: "it",
  sampdoria: "it",
  genoa: "it",
  verona: "it",
  sassuolo: "it",
  cagliari: "it",
  "empoli fc": "it",
  venezia: "it",
  "fc venezia": "it",
  monza: "it",
  spezia: "it",
  salernitana: "it",
  lecce: "it",
  parma: "it",
  // Germany
  "bayern munich": "de",
  "fc bayern": "de",
  "fc bayern münchen": "de",
  "bayern münchen": "de",
  "borussia dortmund": "de",
  "bvb dortmund": "de",
  "rb leipzig": "de",
  "bayer leverkusen": "de",
  "bayer 04 leverkusen": "de",
  wolfsburg: "de",
  "vfl wolfsburg": "de",
  "eintracht frankfurt": "de",
  stuttgart: "de",
  "vfb stuttgart": "de",
  "borussia mönchengladbach": "de",
  "borussia monchengladbach": "de",
  "fc köln": "de",
  "1. fc köln": "de",
  "union berlin": "de",
  "1. fc union berlin": "de",
  "sc freiburg": "de",
  freiburg: "de",
  "fsv mainz 05": "de",
  "mainz 05": "de",
  hoffenheim: "de",
  "tsg 1899 hoffenheim": "de",
  "fc augsburg": "de",
  augsburg: "de",
  "werder bremen": "de",
  schalke: "de",
  "fc schalke 04": "de",
  hertha: "de",
  "hertha bsc": "de",
  // France
  psg: "fr",
  "paris saint-germain": "fr",
  "paris saint germain fc": "fr",
  "paris sg": "fr",
  marseille: "fr",
  "olympique de marseille": "fr",
  "olympique marseille": "fr",
  "om": "fr",
  lyon: "fr",
  "olympique lyonnais": "fr",
  "olympique de lyon": "fr",
  monaco: "fr",
  "as monaco": "fr",
  "as monaco fc": "fr",
  lille: "fr",
  "losc lille": "fr",
  nice: "fr",
  "ogc nice": "fr",
  rennes: "fr",
  "stade rennais": "fr",
  lens: "fr",
  "rc lens": "fr",
  "rc strasbourg alsace": "fr",
  strasbourg: "fr",
  nantes: "fr",
  "fc nantes": "fr",
  montpellier: "fr",
  "montpellier hsc": "fr",
  toulouse: "fr",
  "fc toulouse": "fr",
  bordeaux: "fr",
  "girondins de bordeaux": "fr",
  "fc girondins bordeaux": "fr",
  "stade de reims": "fr",
  reims: "fr",
  brest: "fr",
  "stade brestois": "fr",
  "clermont foot": "fr",
  clermont: "fr",
  auxerre: "fr",
  "aj auxerre": "fr",
  "fc metz": "fr",
  metz: "fr",
  "as saint-étienne": "fr",
  "as saint-etienne": "fr",
  "saint-étienne": "fr",
  "saint-etienne": "fr",
  // Portugal
  porto: "pt",
  "fc porto": "pt",
  benfica: "pt",
  "sl benfica": "pt",
  "sporting cp": "pt",
  "sporting lisbon": "pt",
  "sporting clube de portugal": "pt",
  braga: "pt",
  "sc braga": "pt",
  "sporting braga": "pt",
  "vitória guimarães": "pt",
  "vitoria guimaraes": "pt",
  // Netherlands
  ajax: "nl",
  "afc ajax": "nl",
  psv: "nl",
  "psv eindhoven": "nl",
  feyenoord: "nl",
  "az alkmaar": "nl",
  "az": "nl",
  "fc twente": "nl",
  twente: "nl",
  utrecht: "nl",
  "fc utrecht": "nl",
  // Turkey
  galatasaray: "tr",
  "fenerbahçe": "tr",
  fenerbahce: "tr",
  "beşiktaş": "tr",
  besiktas: "tr",
  trabzonspor: "tr",
  "istanbul başakşehir": "tr",
  // Scotland
  celtic: "gb-sct",
  "celtic fc": "gb-sct",
  rangers: "gb-sct",
  "rangers fc": "gb-sct",
  // Belgium
  "club brugge": "be",
  "club brugge kv": "be",
  anderlecht: "be",
  "rsc anderlecht": "be",
  genk: "be",
  "krc genk": "be",
  "aa gent": "be",
  gent: "be",
  "standard liège": "be",
  "standard de liège": "be",
  "royal antwerp": "be",
  antwerp: "be",
  // Russia
  "zenit st. petersburg": "ru",
  "zenit saint petersburg": "ru",
  zenit: "ru",
  "cska moscow": "ru",
  "pfc cska moscow": "ru",
  "spartak moscow": "ru",
  "fc spartak moscow": "ru",
  "lokomotiv moscow": "ru",
  "fc krasnodar": "ru",
  krasnodar: "ru",
  // Croatia
  "dinamo zagreb": "hr",
  "gnk dinamo zagreb": "hr",
  "hajduk split": "hr",
  // Serbia
  "red star belgrade": "rs",
  "red star": "rs",
  "fk crvena zvezda": "rs",
  "partizan belgrade": "rs",
  "fk partizan": "rs",
  // Switzerland
  basel: "ch",
  "fc basel": "ch",
  "young boys": "ch",
  "bsc young boys": "ch",
  "fc zürich": "ch",
  zurich: "ch",
  // Austria
  "red bull salzburg": "at",
  "fc red bull salzburg": "at",
  salzburg: "at",
  "rapid vienna": "at",
  "sk rapid wien": "at",
  "austria vienna": "at",
  // Ukraine
  "shakhtar donetsk": "ua",
  "fc shakhtar donetsk": "ua",
  "dynamo kyiv": "ua",
  "fc dynamo kyiv": "ua",
  "dynamo kiev": "ua",
  // Greece
  olympiacos: "gr",
  "olympiacos piraeus": "gr",
  paok: "gr",
  "paok fc": "gr",
  panathinaikos: "gr",
  aek: "gr",
  "aek athens": "gr",
  // Czech Republic
  "slavia prague": "cz",
  "sk slavia praha": "cz",
  "sparta prague": "cz",
  "ac sparta praha": "cz",
  "fc viktoria plzeň": "cz",
  "plzeň": "cz",
  // Poland
  "legia warsaw": "pl",
  "legia warszawa": "pl",
  "lech poznan": "pl",
  "wisła kraków": "pl",
  // Denmark
  "fc copenhagen": "dk",
  "fc københavn": "dk",
  copenhagen: "dk",
  "fc midtjylland": "dk",
  "brøndby if": "dk",
  // Sweden
  "malmö": "se",
  "malmö ff": "se",
  "aik": "se",
  "djurgårdens if": "se",
  // Norway
  "rosenborg bk": "no",
  rosenborg: "no",
  "molde fk": "no",
  // Brazil
  flamengo: "br",
  "cr flamengo": "br",
  palmeiras: "br",
  "se palmeiras": "br",
  santos: "br",
  "santos fc": "br",
  "santos futebol clube": "br",
  corinthians: "br",
  "sport club corinthians paulista": "br",
  "são paulo": "br",
  "sao paulo": "br",
  "são paulo fc": "br",
  "gremio": "br",
  "grêmio foot-ball porto alegrense": "br",
  internacional: "br",
  "sc internacional": "br",
  cruzeiro: "br",
  "cruzeiro ec": "br",
  fluminense: "br",
  "fluminense fc": "br",
  "botafogo": "br",
  "atlético mineiro": "br",
  "atlético paranaense": "br",
  "athletico paranaense": "br",
  "fortaleza ec": "br",
  fortaleza: "br",
  bahia: "br",
  "ec bahia": "br",
  // Argentina
  "boca juniors": "ar",
  "ca boca juniors": "ar",
  "river plate": "ar",
  "ca river plate": "ar",
  independiente: "ar",
  "ca independiente": "ar",
  "racing club": "ar",
  "san lorenzo": "ar",
  "ca san lorenzo": "ar",
  "newell's old boys": "ar",
  // Uruguay
  "nacional de football": "uy",
  "club nacional de football": "uy",
  nacional: "uy",
  "peñarol": "uy",
  penarol: "uy",
  "ca peñarol": "uy",
  // USA / Canada
  "inter miami": "us",
  "inter miami cf": "us",
  "la galaxy": "us",
  "los angeles galaxy": "us",
  "new york red bulls": "us",
  "ny red bulls": "us",
  "atlanta united": "us",
  "atlanta united fc": "us",
  "la fc": "us",
  "los angeles fc": "us",
  "seattle sounders": "us",
  "seattle sounders fc": "us",
  "sporting kc": "us",
  "sporting kansas city": "us",
  "philadelphia union": "us",
  "portland timbers": "us",
  "fc dallas": "us",
  "cf montréal": "ca",
  "cf montreal": "ca",
  "toronto fc": "ca",
  "vancouver whitecaps": "ca",
  "vancouver whitecaps fc": "ca",
  // Mexico
  "club américa": "mx",
  "club america": "mx",
  "américa": "mx",
  "chivas": "mx",
  "guadalajara": "mx",
  "cd guadalajara": "mx",
  "cruz azul": "mx",
  "cf pachuca": "mx",
  pachuca: "mx",
  "tigres uanl": "mx",
  "tigres": "mx",
  "monterrey": "mx",
  "cf monterrey": "mx",
  "pumas unam": "mx",
  // Japan
  "kashima antlers": "jp",
  "urawa red diamonds": "jp",
  "yokohama f. marinos": "jp",
  "yokohama f marinos": "jp",
  "kawasaki frontale": "jp",
  "gamba osaka": "jp",
  "nagoya grampus": "jp",
  "cerezo osaka": "jp",
  "fc tokyo": "jp",
  "vissel kobe": "jp",
  // South Korea
  "jeonbuk hyundai motors": "kr",
  "ulsan hyundai": "kr",
  "fc seoul": "kr",
  "suwon samsung bluewings": "kr",
  "pohang steelers": "kr",
  // Australia
  "melbourne city": "au",
  "melbourne victory": "au",
  "sydney fc": "au",
  "western sydney wanderers": "au",
  "brisbane roar": "au",
  "adelaide united": "au",
  "central coast mariners": "au",
  "newcastle jets": "au",
  "perth glory": "au",
  "wellington phoenix": "au",
  // China
  "shanghai port": "cn",
  "shanghai shenhua": "cn",
  "beijing guoan": "cn",
  "guangzhou evergrande": "cn",
  "shandong taishan": "cn",
  // Saudi Arabia
  "al-hilal": "sa",
  "al hilal": "sa",
  "al-nassr": "sa",
  "al nassr": "sa",
  "al-ittihad": "sa",
  "al ittihad": "sa",
  "al-ahli": "sa",
  "al ahli saudi": "sa",
  "al-shabab": "sa",
  "al shabab": "sa",
  // UAE
  "al-ain": "ae",
  "al ain": "ae",
  "al-wahda": "ae",
  "al-nasr": "ae",
  "shabab al-ahli": "ae",
  // Qatar
  "al-sadd": "qa",
  "al sadd": "qa",
  "al-duhail": "qa",
  "al duhail": "qa",
  "al-rayyan": "qa",
  // Egypt
  "al ahly": "eg",
  "al-ahly": "eg",
  "zamalek": "eg",
  "pyramids fc": "eg",
  // Nigeria
  "enugu rangers": "ng",
  "rangers international": "ng",
  // South Africa
  "kaizer chiefs": "za",
  "orlando pirates": "za",
  "mamelodi sundowns": "za",
  // Morocco
  "wydad casablanca": "ma",
  "raja casablanca": "ma",
  // Tunisia
  "espérance sportive de tunis": "tn",
  "esperance": "tn",
  "club africain": "tn",
  // Israel
  "maccabi haifa": "il",
  "maccabi tel aviv": "il",
  "hapoel tel aviv": "il",
  "beitar jerusalem": "il",
  // NBA teams
  "los angeles lakers": "us",
  "golden state warriors": "us",
  "boston celtics": "us",
  "chicago bulls": "us",
  "miami heat": "us",
  "brooklyn nets": "us",
  "new york knicks": "us",
  "philadelphia 76ers": "us",
  "toronto raptors": "ca",
  "dallas mavericks": "us",
  "denver nuggets": "us",
  "milwaukee bucks": "us",
  "phoenix suns": "us",
  "san antonio spurs": "us",
  "houston rockets": "us",
  // NFL teams
  "kansas city chiefs": "us",
  "san francisco 49ers": "us",
  "dallas cowboys": "us",
  "new england patriots": "us",
  "green bay packers": "us",
  "philadelphia eagles": "us",
  "baltimore ravens": "us",
  "buffalo bills": "us",
  "cincinnati bengals": "us",
  "pittsburgh steelers": "us",
  // MLB teams
  "new york yankees": "us",
  "los angeles dodgers": "us",
  "boston red sox": "us",
  "chicago cubs": "us",
  "houston astros": "us",
  // NBA Europe teams
  "real madrid baloncesto": "es",
  "fc barcelona bàsquet": "es",
  "olympiacos bc": "gr",
  "panathinaikos bc": "gr",
  "fenerbahçe basketbol": "tr",
  "cska moscow basketball": "ru",
  // Australian Rules / NRL
  "richmond tigers": "au",
  "collingwood magpies": "au",
  "west coast eagles": "au",
  "essendon bombers": "au",
  // Indian Cricket
  "mumbai indians": "in",
  "chennai super kings": "in",
  "royal challengers bangalore": "in",
  "kolkata knight riders": "in",
  "delhi capitals": "in",
  "rajasthan royals": "in",
  "sunrisers hyderabad": "in",
};

// ── League Name → Country Code ──────────────────────────────────────
// Maps popular league names to their country for flag display
const LEAGUE_COUNTRY_MAP: Record<string, string> = {
  "premier league": "gb-eng",
  "la liga": "es",
  "serie a": "it",
  "bundesliga": "de",
  "ligue 1": "fr",
  "world cup": "eu",
  "champions league": "eu",
  "europa league": "eu",
  "eredivisie": "nl",
  "primeira liga": "pt",
  "super lig": "tr",
  "süper lig": "tr",
  "mls": "us",
  "ligue 2": "fr",
  "serie b": "it",
  "2. bundesliga": "de",
  "championship": "gb-eng",
  "league one": "gb-eng",
  "league two": "gb-eng",
  "fa cup": "gb-eng",
  "copa del rey": "es",
  "dfb pokal": "de",
  "coppa italia": "it",
  "coupe de france": "fr",
  "a league": "au",
  "j league": "jp",
  "k league": "kr",
  "argentine primera division": "ar",
  "brasileirao": "br",
  "brazilian serie a": "br",
  "liga mx": "mx",
};

/**
 * Get the country ISO code for a given country name.
 * Returns null if no match is found.
 */
export function getCountryCode(name: string): string | null {
  const key = name.trim().toLowerCase();
  return COUNTRY_MAP[key] ?? null;
}

/**
 * Get the country ISO code for a given league name.
 * Returns null if no match is found.
 */
export function getLeagueCountryCode(leagueName: string): string | null {
  const key = leagueName.trim().toLowerCase();
  return LEAGUE_COUNTRY_MAP[key] ?? null;
}

/**
 * Get the SVG flag URL for a given country code.
 * Returns null if the code is not in our flag set.
 */
export function getFlagUrl(countryCode: string): string | null {
  // Validate: only letters, hyphens, and dots allowed in filenames
  if (!/^[a-z]{2}(-[a-z]{2,4})?$/.test(countryCode)) return null;
  return `/sections/svg/${countryCode}.svg`;
}

/**
 * Get country code for a team name.
 * Checks in order:
 *   1. TEAM_COUNTRY_MAP (club team name)
 *   2. COUNTRY_MAP (national team name, e.g. "Argentina")
 *   3. All words in the name (handles "Qatar SC", "Real Madrid", "Brazil U20")
 * Returns null if nothing matches.
 */
export function getTeamCountryCode(name: string): string | null {
  const key = name.trim().toLowerCase();

  // 1. Check team-specific map first
  const team = TEAM_COUNTRY_MAP[key];
  if (team) return team;

  // 2. Check country map (full name match)
  const country = COUNTRY_MAP[key];
  if (country) return country;

  // 3. Try all individual words (handles "Qatar SC", "Real Madrid", "Bayern Munich")
  const words = key.split(/\s+/);
  for (const word of words) {
    if (word.length > 1) {
      const w = COUNTRY_MAP[word];
      if (w) return w;
    }
  }

  return null;
}

/**
 * Get flag URL from a country name.
 * Combines lookup + URL generation.
 */
export function getCountryFlagUrl(name: string): string | null {
  const code = getCountryCode(name);
  if (!code) return null;
  return getFlagUrl(code);
}

/**
 * Get flag URL from a league name.
 */
export function getLeagueFlagUrl(leagueName: string): string | null {
  const code = getLeagueCountryCode(leagueName);
  if (!code) return null;
  return getFlagUrl(code);
}
